#!/bin/bash
#Amal Tawakuli
# My first script
E=0
J=0 
M=0
C=0
L=0
while read line; do
	for word in $line; do
		if [[ $word =~ Elizabeth ]]; then
			E=$((E+1))
		fi
		if [[ $word =~ Jane ]]; then
			J=$((J+1))
		fi
		if [[ $word =~ Mary ]]; then
			M=$((M+1))
		fi
		if [[ $word =~ Catherine ]]; then
			C=$((C+1))
		fi
		if [[ $word =~ Lydia ]]; then
			L=$((L+1))
		fi
	done
done <dataSource.txt
echo "Elizabeth occured $E times."
echo "Jane occured $J times."
echo "Mary occured $M times."
echo "Catherine occured $C times."
echo "Lydia occured $L times."